/*
 * latency.c
 *
 * Copyright 2009 by Anthony Howe. All rights reserved.
 */

/***********************************************************************
 *** Leave this header alone. Its generated from the configure script.
 ***********************************************************************/

#include "config.h"

/***********************************************************************
 ***
 ***********************************************************************/

#include "smtpf.h"

#include <com/snert/lib/util/timer.h>

/***********************************************************************
 ***
 ***********************************************************************/

#define LATENCY_REQUEST_TAG	"__lc:"
#define LATENCY_REPLY_TAG	"__lr:"
#define LATENCY_FIELD		"ly="

static char *latency_host;

/*
 * Remote host receives __lc:$host and returns __lr:$host.
 */
static void
latencyClient(mcc_context *mcc, mcc_key_hook *hook, const char *ip, mcc_row *row)
{
	/* Convert __lc to __lr and broadcast. */
	row->key_data[3] = 'r';
	mccSend(mcc, row, MCC_CMD_OTHER);
}

static mcc_key_hook latency_client_hook = {
	NULL,
	LATENCY_REQUEST_TAG, sizeof (LATENCY_REQUEST_TAG)-1,
	latencyClient,
	NULL
};

/*
 * This host receives __lr:$host and computes latency.
 */
static void
latencyReply(mcc_context *mcc, mcc_key_hook *hook, const char *ip, mcc_row *row)
{
	CLOCK now;
	char buffer[32];

	CLOCK_GET(&now);
	CLOCK_SUB(&now, (CLOCK *) row->value_data);
	(void) snprintf(buffer, sizeof (buffer), LATENCY_FIELD CLOCK_FMT, CLOCK_FMT_DOT(now));
	mccNotesUpdate(mcc, ip, LATENCY_FIELD, buffer);
}

static mcc_key_hook latency_reply_hook = {
	NULL,
	LATENCY_REPLY_TAG, sizeof (LATENCY_REPLY_TAG)-1,
	latencyReply,
	NULL
};

void
latencySend(mcc_context *mcc)
{
	mcc_row row;

	if (latency_host != NULL) {
		row.hits = 0;
		row.created = row.touched = time(NULL);
		row.expires = row.created + optCacheGcInterval.value;
		row.key_size = TextCopy((char *) row.key_data, sizeof (row.key_data), latency_host);

		row.value_size = sizeof (CLOCK);
		CLOCK_GET((CLOCK *) row.value_data);
		mccSend(mcc, &row, MCC_CMD_OTHER);
	}
}

void
latencyInit(mcc_context *mcc)
{
	SocketAddress this_host;
	char hostname[SMTP_DOMAIN_LENGTH+32];

	/* Build a special key "__lc:$hostname" used to
	 * identify latency checks generated by this host.
	 */
	memset(&this_host, 0, sizeof (this_host));
	(void) TextCopy(hostname, sizeof (hostname), latency_client_hook.prefix);
	(void) socketAddressGetName(&this_host, hostname+latency_client_hook.prefix_length, sizeof (hostname)-latency_client_hook.prefix_length);
	latency_host = strdup(hostname);

	hostname[3] = 'r';
	latency_reply_hook.prefix = strdup(hostname);
	latency_reply_hook.prefix_length = strlen(hostname);

	mccRegisterKey(mcc, &latency_client_hook);
	mccRegisterKey(mcc, &latency_reply_hook);
}

